version: '3'

services:
  web:
    build: .
    command:  bash -c "cd argos && gunicorn argos.wsgi:application --bind 0.0.0.0:8000"
    container_name: argos
    volumes:
      - .:/argos
    ports:
      - 8000:8000
    env_file:
      - .env