# Generated by Django 4.2.7 on 2023-11-08 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argos_viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDBFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdb'])])),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
