# Generated by Django 4.2.7 on 2023-11-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argos_viewer', '0002_pdbfile_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdbfile',
            name='contents',
            field=models.TextField(default=''),
        ),
    ]
