# Generated by Django 4.2.7 on 2023-11-09 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argos_viewer', '0003_pdbfile_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdbfile',
            name='contents',
        ),
        migrations.AlterField(
            model_name='pdbfile',
            name='pdb_file',
            field=models.FileField(upload_to='pdb_data', validators=[django.core.validators.FileExtensionValidator(['pdb'])]),
        ),
    ]
