# Generated by Django 4.2.7 on 2023-11-15 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('argos_viewer', '0004_remove_pdbfile_contents_alter_pdbfile_pdb_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdbfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
