# Generated by Django 4.2.7 on 2023-11-29 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argos_viewer', '0005_pdbfile_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdbfile',
            name='upload_date',
        ),
        migrations.CreateModel(
            name='TargetPDBFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('pdb_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argos_viewer.pdbfile')),
            ],
        ),
    ]
